### ISSUE TITLE
stucked at api call part,getting the json data but cant use it

### ISSUE THREAD

**Issue by ghost** [chinmay021/fooodvilla#6]
can you help me regarding this.

**Comment by chinmay021** [comment]
[https://github.com/chinmay021/fooodvilla/blob/main/src/components/Body.js](url) refer to getRestaurant function of this file

**Comment by ghost** [comment]
i downloaded your code and tried to run the same,still its not working,there is no error in the console,but body is not displaying after the api calls,i have tried akshay saini bhaiyas code too by cloning the repo to my machine,same result,i think its an issue with the api now,can you pls check chapter6 part of the foodvilla app,header and footer is displaying but body is early returning and if i dont write early return its throwing some ugly 'undefined map ' error.

**Comment by chinmay021** [comment]
git clone the repository.
then npm install
then do ntl dev

try running this way

**Comment by chinmay021** [comment]
closing this issue as it is resolved.

**Comment by chinmay021** [comment]
closing this issue as it is resolved
